name: "Release: graphql-api"
on:
  workflow_dispatch:
    inputs: {}
  push:
    branches:
      - master
jobs:
  release:
    uses: ndlano/reusable-workflows/.github/workflows/release.yaml@main
    secrets: inherit
    with:
      component: graphql-api
